server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: test
  cloud:
    nacos:
      config:
        server-addr: 172.18.81.65:8848
      discovery:
        server-addr: 172.18.81.65:8848